In [52]:
import numpy as np

A = np.array([[1,2,3],[2,4,1],[3,1,0]])

def norme(A):
    return max(abs(A))

print(norme(X))

7


In [54]:
def f(b, A):
    return (np.dot(A,b))/norme(np.dot(A,b))

print(f(X,A))

[1.         0.54166667 0.58333333]


In [73]:
def puissanceIteree(A, k):
    b = np.random.random_sample(len(A))
    for i in range(1,k):
        b = f(A,b)
    return b
print(puissanceIteree(A,5))

[0.71693823 1.         0.53941496]


In [84]:
def vecteurPropre(A,eps=np.finfo(float).eps):
    bk = puissanceIteree(A,0)
    bk1 = f(bk,A)
    while norme(bk1 - bk) > eps and norme(bk1 + bk) > eps :
        bk = bk1
        bk1 = f(bk1,A)
    return bk

print(vecteurPropre(A))

[0.72177255 1.         0.52989832]


In [87]:
print(norme(vecteurPropre(A)))
print(norme(np.dot(A,vecteurPropre(A))))

1.0
5.97344343323562


In [88]:
print(np.linalg.eigvals(A))

[ 5.97344343 -2.58959802  1.61615459]
